# Podman compose file - same as docker-compose
networks:
  backend:
  frontend:

services:
  cache:
    image: redis
    container_name: redis-cache
    networks:
      - backend
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongo-data
    restart: always
    networks:
      - backend
  
  restuarantapi:
    image: ${DOCKER_REGISTRY-}restuarantdemoapi
    container_name: restuarant-api
    networks:
      - backend
      - frontend
    build:
      context: . # context at the root is the path containing the compose file
      dockerfile: Demo.Restuarants.API/Dockerfile
    depends_on:
      - mongo
  
  restuarantclient:
    image: ${DOCKER_REGISTRY-}restuarantmvcclient
    container_name: restuarant-client-mvc
    networks:
      - frontend
    build:
      context: . # context at the root is the path containing the compose file
      dockerfile: Demo.Restuarants.Client.MVC/Dockerfile
    depends_on:
      - restuarantapi
  
  # httpapi:
  #   image: ${DOCKER_REGISTRY-}httpclientapi
  #   container_name: http-api
  #   networks:
  #     - backend
  #   build:
  #     context: .
  #     dockerfile: WebApiHttpClient/Dockerfile
  #   ports:
  #     - 5062:80
  #   depends_on:
  #     - restuarantapi
  #   environment:
  #     - ASPNETCORE_URLS=http://+:80
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - RESTUARANT_API=http://restuarantapi