networks:
  backend:

services:
  cache:
    image: redis
    container_name: redis-cache
    networks:
      - backend
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongo-data
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
  
  restuarantapi:
    image: ${DOCKER_REGISTRY-}restuarantdemoapi
    container_name: restuarant-api
    networks:
      - backend
    build:
      context: . # context at the root is the path containing the compose file
      dockerfile: Demo.Restuarants.API/Dockerfile
    ports:
      - 5017:80
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
  
  # httpapi:
  #   image: ${DOCKER_REGISTRY-}httpclientapi
  #   container_name: http-api
  #   networks:
  #     - backend
  #   build:
  #     context: .
  #     dockerfile: WebApiHttpClient/Dockerfile
  #   ports:
  #     - 5062:80
  #   depends_on:
  #     - restuarantapi
  #   environment:
  #     - ASPNETCORE_URLS=http://+:80
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - RESTUARANT_API=http://restuarantapi